### ISSUE TITLE
Is there a way to not auto-create a folder when saving a fanart?

### ISSUE THREAD

**Issue by tottojambrosi** [leoding86/pixiv-omina#1]
@leoding86 
Sorry for my poor english...
I want to save pixiv works without auto creating a folder for each download.
The settings did not have such option in the "format illust" option.. even if i leave
it blank and save, it still creates a  folder.
Another thing would be that (while using the pixiv toolkit button)every single time pops up the dialogue "open URL:pixiv-omina?" and it's getting on my nerves xd

**Comment by leoding86** [comment]
No need to be sorry for poor English, my english is poor too, just use it. To the issue, You can't leave an empty rename setting. Once I find a way to avoid saving files with same filename, I'll add a setting about don't create subfolder to save files.
About the popup when you click Pixiv Omina, you can't avoid this in Chrome above version 77, because Chrome remove the "always open these types of links in the associated app" option in the dialog base on this [issue](https://bugs.chromium.org/p/chromium/issues/detail?id=982341)

**Comment by leoding86** [comment]
The feature is implemented in version 0.2.0. Close.
