### ISSUE TITLE
插画、漫画的分类识别错误？

### ISSUE THREAD

**Issue by cvk792** [leoding86/pixiv-omina#70]
重命名选项中，我对插画、漫画两个做了不同的目录区分
但是，在下载插画时，会错误地将插画放入到漫画目录下，也就是把链接识别成了漫画分类。

**Comment by sakkamade** [comment]
Sorry I don't know Chinese.
The issue was fixed, read here https://github.com/leoding86/pixiv-omina/issues/67.
New version with [this](https://github.com/leoding86/pixiv-omina/commit/743c8c64217650f5d98e8151b1dd0fce6f164ad3) fix was not released, but the fix is present in current `master`. 
Build the program from source code if you can.
